_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/fast_rcnn_r50_fpn.yml',
  '_base_/fast_fpn_reader.yml',
]
weights: output/fast_rcnn_r50_fpn_1x_coco/model_final
find_unused_parameters: true
